[package]
name = "plug-meta"
version = "0.0.1"
edition = "2018"
publish = false
authors = ["Micha Vie <micha@peerme.io>", "PeerMe <hello@peerme.io>"]

[dev-dependencies]

[dependencies.plug]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.2"
